In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel('housing-1.xlsx')

In [ ]:
df

      X       Y        Xa        Ya
0  1100  199000  0.000000  0.000000
1  1400  245000  0.222222  0.223301
2  1425  319000  0.240741  0.582524
3  1550  240000  0.333333  0.199029
4  1600  312000  0.370370  0.548544
5  1700  279000  0.444444  0.388350
6  1700  310000  0.444444  0.538835
7  1875  308000  0.574074  0.529126
8  2350  405000  0.925926  1.000000
9  2450  324000  1.000000  0.606796

In [ ]:
# y=a+bx



def sum_of_squred_error(xdata,ydata,a,b):
    total_error=0
    for (x,ya) in zip(xdata,ydata):
        yp=a+b*x
        error=(1/2)*(yp-ya)**2
        total_error=total_error+error
    return total_error


a=0.45
b=0.75

print(sum_of_squred_error(df['Xa'],df['Ya'],a,b))

0.6773447764185777

In [ ]:
# y=a+bx

a=0.45
b=0.75

def decrease_gradient_value(xdata,ydata,a,b):
    r=0.01
    total_error=0
    sum_a=0
    sum_b=0
    for (x,ya) in zip(xdata,ydata):
       
        yp=a+b*x
        sum_a= sum_a + (-(ya-yp))
        sum_b= sum_b + (-(ya-yp)*x)

        new_a=a-r*sum_a
        new_b=b-r*sum_b
        error=(1/2)*(yp-ya)**2
        total_error=total_error+error
    return total_error,new_a,new_b




print(sum_of_squred_error(df['Xa'],df['Ya'],a,b))

0.6773447764185777