In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
path="/content/gdrive/MyDrive/ML/DataSets/test.csv"

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(path)

In [5]:
df

         Id  age           job  ... cons.conf.idx euribor3m nr.employed
0     14455   32    management  ...         -42.7     4.961      5228.1
1     36380   37    unemployed  ...         -40.8     1.262      5076.2
2     40076   73       retired  ...         -40.3     0.810      4991.6
3     10778   44  entrepreneur  ...         -41.8     4.961      5228.1
4     27939   28        admin.  ...         -50.0     1.531      5099.1
...     ...  ...           ...  ...           ...       ...         ...
8233  33359   48    management  ...         -46.2     1.291      5099.1
8234  34998   30      services  ...         -46.2     1.250      5099.1
8235  39861   33      services  ...         -39.8     0.720      4991.6
8236   3920   44   blue-collar  ...         -36.4     4.858      5191.0
8237  33395   42   blue-collar  ...         -46.2     1.291      5099.1

[8238 rows x 21 columns]

In [ ]:
df.shape

#It Shows Size Of Our DataFrame

(8238, 21)

In [ ]:
df.head()

#It Print First Five Rows 
#Seeing This Rows We Can Our Data

      Id  age           job  ... cons.conf.idx euribor3m nr.employed
0  14455   32    management  ...         -42.7     4.961      5228.1
1  36380   37    unemployed  ...         -40.8     1.262      5076.2
2  40076   73       retired  ...         -40.3     0.810      4991.6
3  10778   44  entrepreneur  ...         -41.8     4.961      5228.1
4  27939   28        admin.  ...         -50.0     1.531      5099.1

[5 rows x 21 columns]

In [ ]:
df.columns

Index(['Id', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'month', 'day_of_week', 'duration', 'campaign',
       'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='object')

In [ ]:
list_col=df.columns.tolist()
# type(list_col)

list_col
# len(list_col)

['Id',
 'age',
 'job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed']

In [ ]:
df.dtypes

# It Shows Data Types Of All Columns

Id                  int64
age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
dtype: object

In [ ]:
numeric_col=df.describe().columns.tolist()

numeric_col
# len(numeric_col)

#It Shows Numeric columns From DataFrame

['Id',
 'age',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed']

In [ ]:
df.describe()

                 Id          age  ...    euribor3m  nr.employed
count   8238.000000  8238.000000  ...  8238.000000  8238.000000
mean   20492.319738    40.063850  ...     3.632872  5167.580918
std    11851.890912    10.491945  ...     1.728697    71.515506
min        1.000000    17.000000  ...     0.634000  4963.600000
25%    10220.250000    32.000000  ...     1.344000  5099.100000
50%    20486.500000    38.000000  ...     4.857000  5191.000000
75%    30666.250000    47.000000  ...     4.961000  5228.100000
max    41178.000000    98.000000  ...     5.000000  5228.100000

[8 rows x 11 columns]

In [ ]:
df.isnull().sum()

#It Shows Null/NaN Values Of Every Columns In Our DataFrame

Id                0
age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
dtype: int64

In [ ]:
df.nunique()

#It Shows Unique Values In Every Columns

Id                8238
age                 76
job                 12
marital              4
education            8
default              2
housing              3
loan                 3
contact              2
month               10
day_of_week          5
duration          1038
campaign            36
pdays               20
previous             6
poutcome             3
emp.var.rate        10
cons.price.idx      26
cons.conf.idx       26
euribor3m          270
nr.employed         11
dtype: int64

In [ ]:
df1=df.copy()

In [ ]:
df1.head(15)

       Id  age           job  ... cons.conf.idx euribor3m nr.employed
0   14455   32    management  ...         -42.7     4.961      5228.1
1   36380   37    unemployed  ...         -40.8     1.262      5076.2
2   40076   73       retired  ...         -40.3     0.810      4991.6
3   10778   44  entrepreneur  ...         -41.8     4.961      5228.1
4   27939   28        admin.  ...         -50.0     1.531      5099.1
5   37546   45    unemployed  ...         -31.4     0.869      5076.2
6   27310   58        admin.  ...         -42.0     4.021      5195.8
7    8377   46        admin.  ...         -41.8     4.864      5228.1
8   40138   53   blue-collar  ...         -40.3     0.840      4991.6
9   20148   30        admin.  ...         -36.1     4.965      5228.1
10  37959   63    management  ...         -29.8     0.803      5017.5
11  16213   39   blue-collar  ...         -42.7     4.961      5228.1
12  28763   59   blue-collar  ...         -47.1     1.410      5099.1
13  24077   57        admin.  ...         -42.0     4.663      5195.8
14   7334   46    management  ...         -36.4     4.864      5191.0

[15 rows x 21 columns]

In [ ]:
df1.columns

Index(['Id', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'month', 'day_of_week', 'duration', 'campaign',
       'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='object')

In [ ]:
df1[(df1['age']>50) & (df1['marital']=='divorced')]

         Id  age         job  ... cons.conf.idx euribor3m nr.employed
2     40076   73     retired  ...         -40.3     0.810      4991.6
6     27310   58      admin.  ...         -42.0     4.021      5195.8
13    24077   57      admin.  ...         -42.0     4.663      5195.8
24    28139   55  management  ...         -47.1     1.466      5099.1
46     9855   52      admin.  ...         -41.8     4.959      5228.1
...     ...  ...         ...  ...           ...       ...         ...
8168  11134   54     retired  ...         -41.8     4.961      5228.1
8173  26066   56  management  ...         -42.0     4.120      5195.8
8187   9782   54   housemaid  ...         -41.8     4.959      5228.1
8213   2030   55  technician  ...         -36.4     4.857      5191.0
8226  17524   51      admin.  ...         -42.7     4.962      5228.1

[269 rows x 21 columns]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# # plt.hist(df1['marital'],df['job'])
# plt.xlabel("Marital")
# # plt.color("red")

In [ ]:
df1=df1.loc[:,['age','job','marital','housing','loan','duration',]]

In [ ]:
df1['marital'].unique()

array(['divorced', 'unknown', 'married', 'single'], dtype=object)

In [ ]:
df1[df1['marital']=='unknown'].shape

(15, 6)

In [ ]:
df1[df1['marital']=='divorced'].shape

(937, 6)

In [ ]:
df1['marital'].mode()

0    married
dtype: object

In [ ]:
df1['marital']=df['marital'].replace('unknown',df1['marital'].mode()[0])

In [ ]:
df1['marital'].unique()

array(['divorced', 'married', 'single'], dtype=object)